//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public bool Sex { get; set; }
        public int PositionId { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
